# Dungeons and Dragons TidyTuesday plot

# Setup ----

# Load in data 
tuesdata <- tidytuesdayR::tt_load('2024-12-17')
spells <- tuesdata$spells

# Load required packages
library(tidyverse)
library(ggforce)
library(ggimage)
library(showtext)
library(patchwork)

# Create a "not in" function
`%ni%` <- negate(`%in%`) 

# Add font
font_add_google("MedievalSharp", family = "special")
showtext_auto()

# Creating color palettes ----
# Creating a data frame with community-defined colors for each class, and path to class icon, along with plot size scalar for each icon
class_cols <- tribble(
  ~"class", ~"color",~"image", ~"size",
  "bard","#AB6DAC", "icons/svgs/Bard.svg",0.2,
  "cleric","#91A1B2","icons/svgs/Cleric.svg",0.25,
  "druid","#7A853B","icons/svgs/Druid.svg",0.17,
  "paladin","#B59E54","icons/svgs/Paladin.svg",0.12,
  "ranger", "#507F62","icons/svgs/Ranger.svg",0.19,
  "sorcerer", "#992E2E","icons/svgs/Sorcerer.svg",0.14,
  "warlock", "#7B469B","icons/svgs/Warlock.svg",0.2,
  "wizard", "#2A50A1","icons/svgs/Wizard.svg",0.17
)

# General color associated with each school of magic that I could find from community
school_cols <- tribble(
  ~"school",~"color",
  "abjuration", "blue",
  "conjuration", "yellow",
  "divination", "gray",
  "enchantment", "pink",
  "evocation",  "red",
  "illusion", "purple",
  "necromancy", "green",
  "transmutation","orange"
)

# DnD color palette generated by chat gpt using the general colors above 
color_palette <- tribble(
  ~Color_Theme, ~Shade_Name,         ~Hex_Code,
  "Blue",       "Arcane Sapphire",   "#2A4E8C",
  "Blue",       "Frostbite Blue",    "#7CA9D4",
  "Yellow",     "Sunforged Gold",    "#EAC64D",
  "Yellow",     "Candelabra Flame",  "#FFD86E",
  "Gray",       "Stonekeep Gray",    "#6B6E70",
  "Gray",       "Specter Smoke",     "#A9AAAE",
  "Pink",       "Feywild Bloom",     "#D881A3",
  "Pink",       "Charm Person",      "#F2B3C1",
  "Red",        "Dragonfire Red",    "#B31C24",
  "Red",        "Blood Oath",        "#7E1B1B",
  "Purple",     "Eldritch Veil",     "#5A3E82",
  "Purple",     "Amethyst Arcana",   "#A58BCC",
  "Green",      "Venomfang",         "#4A9A57",
  "Green",      "Forest Guardian",   "#88B57F",
  "Orange",     "Emberglow",         "#D96E30",
  "Orange",     "Goblin Torch",      "#FF9A3E"
)

# Picking one of each broad color from above
gpt_palette <- tribble(
  ~color, ~Shade_Name,         ~hex,
  "blue",       "Frostbite Blue",    "#7CA9D4",
  "yellow",     "Sunforged Gold",    "#EAC64D",
  "gray",       "Stonekeep Gray",    "#6B6E70",
  "pink",       "Charm Person",      "#F2B3C1",
  "red",        "Blood Oath",        "#7E1B1B",
  "purple",     "Eldritch Veil",     "#5A3E82",
  "green",      "Venomfang",         "#4A9A57",
  "orange",     "Goblin Torch",      "#FF9A3E"
)

# Joining with original school cols dataframe.
school_cols <- left_join(school_cols,
                         gpt_palette,
                         by="color")

# Data wrangling ----

# Creating smaller dataframe with only columns of interest
spells_short <- spells[,1:11]

# Pivoting to long format with class as a column
spells_short_long <- spells_short %>% 
  pivot_longer(-c(1:3), 
               names_to = "class",
               values_to = "castable")

# Summary table of number of spells within each school of magic that are castable by each class
school_class <- spells_short_long %>% 
  group_by(school,class) %>% 
  summarise(n = sum(castable))

# Adding a "scale" column that is the proportion of spells a given school is for the total a class can cast
school_class <- school_class %>% 
  group_by(class) %>% 
  mutate(scale = (n/max(n))*0.9) %>% 
  ungroup()

# Creating separate data frame for first four schools, spell-lines that curve upwards
## start is Pi and end is some scaled distance to pi/2 on perimeter of a circle
## The "scale" column controls how mcuh of the distance between those two end points a spell-line covers
## r is radius of circle within geom_arc function, x0 and y0 are center of the circle. The transformations used were
## picked for best arrangement.
school_class_a <- school_class %>% 
  filter(school%in%c("abjuration","conjuration","divination","enchantment")) %>% 
  mutate(start = pi, 
         end = pi - ((pi-(pi/2))*scale),
         r = 1+scale,
         x0=0,
         y0=3+scale)

# Creating separate data frame for second four schools, spell-lines that curve downwards
## Same process as above, except now between pi/2 and 0
school_class_b <- school_class %>% 
  filter(school%ni%c("abjuration","conjuration","divination","enchantment")) %>% 
  mutate(start = 0, 
         end = 0 + (((pi/2)-0)*scale),
         r = 1+scale,
         x0=0,
         y0=1-scale)

# Binding the two dataframes created above back together
school_class_all <- rbind(school_class_a,school_class_b)
# Joining with school_cols dataframe for colors
school_class_all <- left_join(school_class_all,
                              school_cols,
                              by="school")

# Summarizing spells within each school by "range type"
spells_rangt <- spells %>% 
  group_by(school, range_type) %>% 
  summarize(n = n()) %>% 
  group_by(range_type) %>% 
  mutate(p = n/sum(n))

# Separate summary of spells within each school
spells_total <- spells %>% 
  group_by(school) %>% 
  summarize(n = n()) %>% 
  mutate(p = n/sum(n),
         range_type = "overall")

# Binding above two dfs together, then joining with school_cols
spells_rangt <- rbind(spells_rangt, spells_total) %>%
  right_join(school_cols, by = "school")
# Chaning range type of "feet" to "ranged"
spells_rangt$range_type[which(spells_rangt$range_type == "feet")] <- "ranged"

# Changing factor levels of range_type
spells_rangt <- spells_rangt %>%
  mutate(range_type = factor(
    range_type,
    levels = c("ranged", "self", "touch", "sight", "other", "overall", " ")
  ))

# Center panel ---- 
# Creating dataframe for color coded school labels to plot next to "overall" column 
spells_text <- school_cols %>% mutate(
  range_type = " ",
  y = c(0.925,
        0.775,
        0.65,
        0.55,
        0.425,
        0.325,
        0.225,
        0.1)
) %>%
  mutate(range_type = factor(
    range_type,
    levels = c("ranged", "self", "touch", "sight", "other", "overall", " ")
  ))

# df to plot white box for overall column 
ov_box <- tibble(range_type = "overall",
                 y = 1)

# Central plot - columns of spell shools by range_type
C <- ggplot(spells_rangt) +
  geom_col(aes(x = range_type,
               y = p,
               fill = school)) +
  geom_col(
    data = ov_box,
    aes(x = range_type, y = y),
    color = "white",
    fill = "transparent",
    linewidth = 1
  ) +
  geom_text(
    data = spells_text ,
    aes(
      x = range_type,
      y = y,
      label = school,
      color = school
    ),
    size = 5,
    family = "special"
  ) +
  labs(title = "Range Type",
       subtitle = "Key:") +
  scale_y_continuous(expand = c(0.001, 0.001)) +
  scale_fill_manual(values = school_cols$hex) +
  scale_color_manual(values = school_cols$hex) +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.background = element_rect(fill = "#1D1D1D", color = "#1D1D1D"),
    plot.background =  element_rect(fill = "#1D1D1D"),
    panel.grid = element_blank(),
    axis.ticks = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = element_text(
      color = "white",
      vjust = 0,
      size = 12
    ),
    axis.title = element_blank(),
    plot.subtitle = element_text(hjust = 0.925),
    legend.position = 'none',
    text = element_text(color = "white", family = "special")
  )

# Left panel ----

# Creating df for example spell at bottom of left panel of "spell-lines" plot
lo <- 50 # length out constant
ex_spell_L <- data_frame(
  x = seq(0, 1.9, length.out = lo),
  y = rep(0, lo),
  index = seq(0, 1, length.out = lo),
  class = "paladin"
)

# Data frame for "less/more" labels above example spell line, left side
lab_spell_L <- data_frame(x=c(0.1,1.8),
                        y=0.4,
                        class="paladin",
                        label= c("fewer","more")
)

# Pulling out first four classes for left hand panel
school_class_left <- school_class_all %>% 
  filter(class%in%c("bard" ,"cleric","druid","paladin"))
# Same for colors
class_cols_left <- class_cols %>% 
  filter(class%in%c("bard" ,"cleric","druid","paladin"))

# Plotting left panel
L <- ggplot(school_class_left) +
  geom_line(
    data = ex_spell_L,
    aes(x = x,
        y = y,
        size = index ^ 4),
    lineend = 'round',
    color = "white"
  ) +
  geom_text(aes(x = 0.1, y = 2.5, label = class),
            color = 'white',
            family = "special") +
  geom_text(
    data = lab_spell_L,
    aes(x = x, y = y, label = label),
    color = 'white',
    family = "special"
  ) +
  geom_arc(
    aes(
      x0 = x0,
      y0 = y0,
      r = r,
      start = start,
      end = end,
      color = school,
      size = after_stat(index) ^ 3
    ),
    lineend = 'round'
  ) +
  scale_color_manual(values = school_cols$hex) +
  scale_size(guide = 'none') +
  geom_point(
    data = class_cols_left,
    aes(x = 1.55, y = 2, fill = color),
    shape = 21,
    size = 20,
    color = "white"
  ) +
  #geom_image(  # Note: I did not include the images folder online, so I have removed this call for code to run properly
   # data = class_cols_left,
    #aes(x = 1.55, y = 2, image = image),
    #size = class_cols_left$size,
    #color = "white"
  #) +
  scale_fill_identity() +
  facet_wrap( ~ class, ncol = 1) +
  theme_void() +
  theme(
    panel.background = element_rect(fill = "#1D1D1D", color = "#1D1D1D"),
    strip.background = element_blank(),
    strip.text.x.top = element_blank(),
    plot.background =  element_rect(fill = "#1D1D1D"),
    legend.position = 'none',
    strip.text = element_text(size = 12),
    text = element_text(color = "white", family = "special")
  )

# Right panel ----
# Same as for above, but for last four and right hand panel
school_class_right <-
  school_class_all %>% filter(class %ni% c("bard" , "cleric", "druid", "paladin"))
class_cols_right <-
  class_cols %>% filter(class %ni% c("bard" , "cleric", "druid", "paladin"))

lab_spell_R <- data_frame(
  x = c(0.1, 1.65),
  y = 0.4,
  class = "wizard",
  label = c("fewer", "more")
)
ex_spell_R <- data_frame(
  x = seq(0, 1.9, length.out = lo),
  y = rep(0, lo),
  index = seq(0, 1, length.out = lo),
  class = "wizard"
)

R <- ggplot(school_class_right) +
  geom_line(
    data = ex_spell_R,
    aes(x = x,
        y = y,
        size = index ^ 4),
    lineend = 'round',
    color = "white"
  ) +
  geom_text(aes(x = 0.1, y = 2.5, label = class),
            color = 'white',
            family = "special") +
  geom_text(
    data = lab_spell_R,
    aes(x = x, y = y, label = label),
    color = 'white',
    family = "special"
  ) +
  geom_arc(
    aes(
      x0 = x0,
      y0 = y0,
      r = r,
      start = start,
      end = end,
      color = school,
      size = after_stat(index) ^ 3
    ),
    lineend = 'round'
  ) +
  scale_color_manual(values = school_cols$hex) +
  scale_size(guide = 'none') +
  geom_point(
    data = class_cols_right,
    aes(x = 1.55, y = 2, fill = color),
    shape = 21,
    size = 20,
    color = "white"
  ) +
 # geom_image( # Note: I did not include the images folder online, so I have removed this call for code to run properly
  #  data = class_cols_right,
   # aes(x = 1.55, y = 2, image = image),
   # size = class_cols_right$size,
    #color = "white"
  #) +
  scale_fill_identity() +
  facet_wrap( ~ class, ncol = 1) +
  theme_void() +
  theme(
    panel.background = element_rect(fill = "#1D1D1D", color = "#1D1D1D"),
    plot.background =  element_rect(fill = "#1D1D1D"),
    strip.background = element_blank(),
    strip.text.x.top = element_blank(),
    strip.placement = 'none',
    legend.position = 'none',
    strip.text = element_text(size = 12),
    text = element_text(color = "white", family = "special")
  )


# Putting it all together ----

# Defining layout for 3 panel plot 
design <- "
ABBBC
" 

L + C + R + plot_annotation(
  title = "Spell-school is in session!",
  subtitle = "Center: Proportion of each spell range type that is of a certain school of magic. Colors correspond to school, stacked/listed alphabetically to the right of the 'overall' column.
Outer: Lines scale to the proportion of number of spells within each school of magic a given class can cast,e.g., the vast majority of spells a Paladin can cast are of the abjuration school.
  Line colors correspond to colors in center panel.",
caption = "@benuveges.bsky.social",
theme = theme(text = element_text(
  color = "white",
  family = "special",
  size = 13
))
) + plot_layout(design = design) &
  theme(plot.background = element_rect(fill = "#1D1D1D", color = "#1D1D1D"))
